### ISSUE TITLE
Review tekst over CityGML en CityJSON

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/hr-3d-standaarden#1]
> Het nadeel van CityJSON is echter dat het sommige complexe topologische relaties, zoals die met water of terrein, niet volledig ondersteunt.

Is dit zo? CityJSON is op hetzelfde datamodel als CityGML gebaseerd en zou dus ook dezelfde dingen moeten kunnen. Er zijn wat beperkingen, die zijn [hier](https://www.cityjson.org/citygml/v30/ beschreven. Kunnen we specifiek naar de beperking verwijzen die ervoor zorgt dat sommige complexe topologische relaties niet met CityJSON beschreven kunnen worden?

> vaak wordt een CityGML-bestand door CityJSON met een factor 3 tot 6 verkleind. 

Op https://www.cityjson.org/ wordt gezegd dat het formaat gemiddeld 7x zo compact is als CityGML.

> {CityJSON is] voornamelijk gericht op analyse in plaats van visualisatie en wordt gebruikt in statische toepassingen, zoals stedelijke planning en 3D-dataverwerking.

CityJSON kun je ook streamen, zie https://www.cityjson.org/cityjsonseq/, dit maakt het makkelijker om met zeer grote bestanden te werken.

> CityGML daarentegen is een complexere standaard die zeer gedetailleerde semantische informatie biedt

CityJSON biedt hetzelfde semantische detailniveau dus je kunt er net zo gedetailleerd een stad mee modelleren, behalve dat er voor gekozen is om een aantal zaken uit de standaard niet te ondersteunen. Bv Dynamizers, waarmee je dynamische data aan je stadsmodel kan hangen. 

Iets wat met CityGML beter kan omdat het op XML gebaseerd is, is validatie van de bestandsstructuur. Al zal dat in de praktijk vaak lastig zijn omdat validators niet met erg grote bestanden om kunnen gaan.

> Een kernconcept binnen CityGML is het gebruik van niveaus van detail (Levels of Detail, LOD).

CityJSON ondersteunt ook levels of detail, maak duidelijk dat dat niet een verschil tussen beide is. 

Hoe zit het met software ondersteuning van CityJSON? Hierover geeft het stuk nog niet zoveel informatie. Zie https://www.cityjson.org/software/

**Comment by ynekevierselGeonovum** [comment]
"Is dit zo? CityJSON is op hetzelfde datamodel als CityGML gebaseerd en zou dus ook dezelfde dingen moeten kunnen. Er zijn wat beperkingen, die zijn [hier](https://www.cityjson.org/citygml/v30/ beschreven. Kunnen we specifiek naar de beperking verwijzen die ervoor zorgt dat sommige complexe topologische relaties niet met CityJSON beschreven kunnen worden?"

Als reactie hierop: bedankt voor het doorsturen van het linkje! wat daarin staat inderdaad als 3e punt "topological relationships, eg relativeToTerrain and relativeToWater, which qualify relationships, are not supported.". Dus dan kan ik de tekst onderbouwen met de bron die je erbij hebt gezet.
