### ISSUE TITLE
Kleine taaldingetjes

### ISSUE THREAD

**Issue by EricOosterom** [Geonovum/hr-3d-standaarden#7]
Als taalpurist (slechts) vier dingen die me opvielen. Dank voor het informatieve en duidelijke stuk!

In 2.1 "CityGML daarentegen is een uitgebreidere standaard evenveel gedetailleerde semantische informatie biedt" mist waarschijnlijk 'die' tussen standaard en evenveel 

In 2.2.1 staat "Als je werkt in een globale context en geografische projectie (zoals WGS1984)." Wordt echt globaal (=in grote lijnen) bedoeld, of gaat het om mondiaal/wereldwijd? Het is de veelgemaakte vertaalfout van het Engelse 'global'.

In 2.3 "Deze standaard is ontwikkeld door Esri en is een landing page over I3S" mist 'er' tussen en en is.  

In 2.3.1 "Snelle data-invoer van zowel feature layers, mesh layers en point cloud layers." kiezen tussen 'zowel ... als' of 'en' als vorm voor een opsomming. Vermengen is niet fraai.

**Comment by ynekevierselGeonovum** [comment]
bedankt voor de suggesties, zojuist is jouw input verwerkt.
